[build]
  publish = "dist/"
  command = "NODE_ENV=development npm ci && npm run build"
  environment = { TZ = "America/Chicago" }

[context.old]
  publish = "/"
  command = ""

[[redirects]]
  from = "/send/*"
  to = "https://dpaste.com/api/v2/:splat"
  status = 200

[[redirects]]
  from = "/receive/*"
  to = "https://dpaste.com/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
